# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 991045b68d3857be68701a0b4be64f6a469211b89a65e70c6129f6c9b14c4a3b56975abe7875edc6630630f4a37b1181084d36adc5c20d077c828895c788f1ce

test:
  secret_key_base: eae6dd82c4ecc492fc1e3b2a6f6576327020b972763e55a9edbf45f679e0cb5480a12b517738e84b46100dc4ad073e74009175cf763cf4a08e18bc58f022cbe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
